// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ensina_renda.proto

package grpc

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CadastrarAlunoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Nome           string                 `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Senha          string                 `protobuf:"bytes,3,opt,name=senha,proto3" json:"senha,omitempty"`
	DataNascimento string                 `protobuf:"bytes,4,opt,name=data_nascimento,json=dataNascimento,proto3" json:"data_nascimento,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CadastrarAlunoRequest) Reset() {
	*x = CadastrarAlunoRequest{}
	mi := &file_ensina_renda_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CadastrarAlunoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CadastrarAlunoRequest) ProtoMessage() {}

func (x *CadastrarAlunoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CadastrarAlunoRequest.ProtoReflect.Descriptor instead.
func (*CadastrarAlunoRequest) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{0}
}

func (x *CadastrarAlunoRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *CadastrarAlunoRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CadastrarAlunoRequest) GetSenha() string {
	if x != nil {
		return x.Senha
	}
	return ""
}

func (x *CadastrarAlunoRequest) GetDataNascimento() string {
	if x != nil {
		return x.DataNascimento
	}
	return ""
}

type CadastrarAlunoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensagem      string                 `protobuf:"bytes,1,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	Sucesso       bool                   `protobuf:"varint,2,opt,name=sucesso,proto3" json:"sucesso,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CadastrarAlunoResponse) Reset() {
	*x = CadastrarAlunoResponse{}
	mi := &file_ensina_renda_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CadastrarAlunoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CadastrarAlunoResponse) ProtoMessage() {}

func (x *CadastrarAlunoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CadastrarAlunoResponse.ProtoReflect.Descriptor instead.
func (*CadastrarAlunoResponse) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{1}
}

func (x *CadastrarAlunoResponse) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

func (x *CadastrarAlunoResponse) GetSucesso() bool {
	if x != nil {
		return x.Sucesso
	}
	return false
}

var File_ensina_renda_proto protoreflect.FileDescriptor

const file_ensina_renda_proto_rawDesc = "" +
	"\n" +
	"\x12ensina_renda.proto\x12\fensina_renda\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"\x94\x01\n" +
	"\x15CadastrarAlunoRequest\x12\x17\n" +
	"\x04nome\x18\x01 \x01(\tB\x03\xe0A\x02R\x04nome\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tB\x03\xe0A\x02R\x05email\x12\x19\n" +
	"\x05senha\x18\x03 \x01(\tB\x03\xe0A\x02R\x05senha\x12,\n" +
	"\x0fdata_nascimento\x18\x04 \x01(\tB\x03\xe0A\x02R\x0edataNascimento\"N\n" +
	"\x16CadastrarAlunoResponse\x12\x1a\n" +
	"\bmensagem\x18\x01 \x01(\tR\bmensagem\x12\x18\n" +
	"\asucesso\x18\x02 \x01(\bR\asucesso2\x88\x01\n" +
	"\x12EnsinaRendaService\x12r\n" +
	"\x0eCadastrarAluno\x12#.ensina_renda.CadastrarAlunoRequest\x1a$.ensina_renda.CadastrarAlunoResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/alunosB\bZ\x06.;grpcb\x06proto3"

var (
	file_ensina_renda_proto_rawDescOnce sync.Once
	file_ensina_renda_proto_rawDescData []byte
)

func file_ensina_renda_proto_rawDescGZIP() []byte {
	file_ensina_renda_proto_rawDescOnce.Do(func() {
		file_ensina_renda_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ensina_renda_proto_rawDesc), len(file_ensina_renda_proto_rawDesc)))
	})
	return file_ensina_renda_proto_rawDescData
}

var file_ensina_renda_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ensina_renda_proto_goTypes = []any{
	(*CadastrarAlunoRequest)(nil),  // 0: ensina_renda.CadastrarAlunoRequest
	(*CadastrarAlunoResponse)(nil), // 1: ensina_renda.CadastrarAlunoResponse
}
var file_ensina_renda_proto_depIdxs = []int32{
	0, // 0: ensina_renda.EnsinaRendaService.CadastrarAluno:input_type -> ensina_renda.CadastrarAlunoRequest
	1, // 1: ensina_renda.EnsinaRendaService.CadastrarAluno:output_type -> ensina_renda.CadastrarAlunoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ensina_renda_proto_init() }
func file_ensina_renda_proto_init() {
	if File_ensina_renda_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ensina_renda_proto_rawDesc), len(file_ensina_renda_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ensina_renda_proto_goTypes,
		DependencyIndexes: file_ensina_renda_proto_depIdxs,
		MessageInfos:      file_ensina_renda_proto_msgTypes,
	}.Build()
	File_ensina_renda_proto = out.File
	file_ensina_renda_proto_goTypes = nil
	file_ensina_renda_proto_depIdxs = nil
}
