// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        (unknown)
// source: ensina_renda.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CriarUsuarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nome          string                 `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Senha         string                 `protobuf:"bytes,3,opt,name=senha,proto3" json:"senha,omitempty"`
	DataCriacao   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=data_criacao,json=dataCriacao,proto3" json:"data_criacao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriarUsuarioRequest) Reset() {
	*x = CriarUsuarioRequest{}
	mi := &file_ensina_renda_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriarUsuarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriarUsuarioRequest) ProtoMessage() {}

func (x *CriarUsuarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriarUsuarioRequest.ProtoReflect.Descriptor instead.
func (*CriarUsuarioRequest) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{0}
}

func (x *CriarUsuarioRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *CriarUsuarioRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CriarUsuarioRequest) GetSenha() string {
	if x != nil {
		return x.Senha
	}
	return ""
}

func (x *CriarUsuarioRequest) GetDataCriacao() *timestamppb.Timestamp {
	if x != nil {
		return x.DataCriacao
	}
	return nil
}

type CriarUsuarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensagem      string                 `protobuf:"bytes,1,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	Sucesso       bool                   `protobuf:"varint,2,opt,name=sucesso,proto3" json:"sucesso,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriarUsuarioResponse) Reset() {
	*x = CriarUsuarioResponse{}
	mi := &file_ensina_renda_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriarUsuarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriarUsuarioResponse) ProtoMessage() {}

func (x *CriarUsuarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriarUsuarioResponse.ProtoReflect.Descriptor instead.
func (*CriarUsuarioResponse) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{1}
}

func (x *CriarUsuarioResponse) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

func (x *CriarUsuarioResponse) GetSucesso() bool {
	if x != nil {
		return x.Sucesso
	}
	return false
}

var File_ensina_renda_proto protoreflect.FileDescriptor

var file_ensina_renda_proto_rawDesc = []byte{
	0x0a, 0x12, 0x65, 0x6e, 0x73, 0x69, 0x6e, 0x61, 0x5f, 0x72, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x65, 0x6e, 0x73, 0x69, 0x6e, 0x61, 0x5f, 0x72, 0x65, 0x6e,
	0x64, 0x61, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x94, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x69, 0x61, 0x72, 0x55, 0x73, 0x75,
	0x61, 0x72, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x12, 0x3d, 0x0a, 0x0c, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x63, 0x72, 0x69, 0x61, 0x63, 0x61, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x64,
	0x61, 0x74, 0x61, 0x43, 0x72, 0x69, 0x61, 0x63, 0x61, 0x6f, 0x22, 0x4c, 0x0a, 0x14, 0x43, 0x72,
	0x69, 0x61, 0x72, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x32, 0x6b, 0x0a, 0x12, 0x45, 0x6e, 0x73, 0x69,
	0x6e, 0x61, 0x52, 0x65, 0x6e, 0x64, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55,
	0x0a, 0x0c, 0x43, 0x72, 0x69, 0x61, 0x72, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x21,
	0x2e, 0x65, 0x6e, 0x73, 0x69, 0x6e, 0x61, 0x5f, 0x72, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x43, 0x72,
	0x69, 0x61, 0x72, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x65, 0x6e, 0x73, 0x69, 0x6e, 0x61, 0x5f, 0x72, 0x65, 0x6e, 0x64, 0x61,
	0x2e, 0x43, 0x72, 0x69, 0x61, 0x72, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ensina_renda_proto_rawDescOnce sync.Once
	file_ensina_renda_proto_rawDescData = file_ensina_renda_proto_rawDesc
)

func file_ensina_renda_proto_rawDescGZIP() []byte {
	file_ensina_renda_proto_rawDescOnce.Do(func() {
		file_ensina_renda_proto_rawDescData = protoimpl.X.CompressGZIP(file_ensina_renda_proto_rawDescData)
	})
	return file_ensina_renda_proto_rawDescData
}

var file_ensina_renda_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ensina_renda_proto_goTypes = []any{
	(*CriarUsuarioRequest)(nil),   // 0: ensina_renda.CriarUsuarioRequest
	(*CriarUsuarioResponse)(nil),  // 1: ensina_renda.CriarUsuarioResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_ensina_renda_proto_depIdxs = []int32{
	2, // 0: ensina_renda.CriarUsuarioRequest.data_criacao:type_name -> google.protobuf.Timestamp
	0, // 1: ensina_renda.EnsinaRendaService.CriarUsuario:input_type -> ensina_renda.CriarUsuarioRequest
	1, // 2: ensina_renda.EnsinaRendaService.CriarUsuario:output_type -> ensina_renda.CriarUsuarioResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ensina_renda_proto_init() }
func file_ensina_renda_proto_init() {
	if File_ensina_renda_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ensina_renda_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ensina_renda_proto_goTypes,
		DependencyIndexes: file_ensina_renda_proto_depIdxs,
		MessageInfos:      file_ensina_renda_proto_msgTypes,
	}.Build()
	File_ensina_renda_proto = out.File
	file_ensina_renda_proto_rawDesc = nil
	file_ensina_renda_proto_goTypes = nil
	file_ensina_renda_proto_depIdxs = nil
}
