// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ensina_renda.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnsinaRendaService_CadastrarAluno_FullMethodName = "/ensina_renda.EnsinaRendaService/CadastrarAluno"
)

// EnsinaRendaServiceClient is the client API for EnsinaRendaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnsinaRendaServiceClient interface {
	CadastrarAluno(ctx context.Context, in *CadastrarAlunoRequest, opts ...grpc.CallOption) (*CadastrarAlunoResponse, error)
}

type ensinaRendaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnsinaRendaServiceClient(cc grpc.ClientConnInterface) EnsinaRendaServiceClient {
	return &ensinaRendaServiceClient{cc}
}

func (c *ensinaRendaServiceClient) CadastrarAluno(ctx context.Context, in *CadastrarAlunoRequest, opts ...grpc.CallOption) (*CadastrarAlunoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CadastrarAlunoResponse)
	err := c.cc.Invoke(ctx, EnsinaRendaService_CadastrarAluno_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnsinaRendaServiceServer is the server API for EnsinaRendaService service.
// All implementations must embed UnimplementedEnsinaRendaServiceServer
// for forward compatibility.
type EnsinaRendaServiceServer interface {
	CadastrarAluno(context.Context, *CadastrarAlunoRequest) (*CadastrarAlunoResponse, error)
	mustEmbedUnimplementedEnsinaRendaServiceServer()
}

// UnimplementedEnsinaRendaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnsinaRendaServiceServer struct{}

func (UnimplementedEnsinaRendaServiceServer) CadastrarAluno(context.Context, *CadastrarAlunoRequest) (*CadastrarAlunoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CadastrarAluno not implemented")
}
func (UnimplementedEnsinaRendaServiceServer) mustEmbedUnimplementedEnsinaRendaServiceServer() {}
func (UnimplementedEnsinaRendaServiceServer) testEmbeddedByValue()                            {}

// UnsafeEnsinaRendaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnsinaRendaServiceServer will
// result in compilation errors.
type UnsafeEnsinaRendaServiceServer interface {
	mustEmbedUnimplementedEnsinaRendaServiceServer()
}

func RegisterEnsinaRendaServiceServer(s grpc.ServiceRegistrar, srv EnsinaRendaServiceServer) {
	// If the following call pancis, it indicates UnimplementedEnsinaRendaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnsinaRendaService_ServiceDesc, srv)
}

func _EnsinaRendaService_CadastrarAluno_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CadastrarAlunoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnsinaRendaServiceServer).CadastrarAluno(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnsinaRendaService_CadastrarAluno_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnsinaRendaServiceServer).CadastrarAluno(ctx, req.(*CadastrarAlunoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnsinaRendaService_ServiceDesc is the grpc.ServiceDesc for EnsinaRendaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnsinaRendaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ensina_renda.EnsinaRendaService",
	HandlerType: (*EnsinaRendaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CadastrarAluno",
			Handler:    _EnsinaRendaService_CadastrarAluno_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ensina_renda.proto",
}
