// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: ensina_renda.proto

package grpc

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CadastrarAlunoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Nome           string                 `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Senha          string                 `protobuf:"bytes,3,opt,name=senha,proto3" json:"senha,omitempty"`
	DataNascimento string                 `protobuf:"bytes,4,opt,name=data_nascimento,json=dataNascimento,proto3" json:"data_nascimento,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CadastrarAlunoRequest) Reset() {
	*x = CadastrarAlunoRequest{}
	mi := &file_ensina_renda_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CadastrarAlunoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CadastrarAlunoRequest) ProtoMessage() {}

func (x *CadastrarAlunoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CadastrarAlunoRequest.ProtoReflect.Descriptor instead.
func (*CadastrarAlunoRequest) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{0}
}

func (x *CadastrarAlunoRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *CadastrarAlunoRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CadastrarAlunoRequest) GetSenha() string {
	if x != nil {
		return x.Senha
	}
	return ""
}

func (x *CadastrarAlunoRequest) GetDataNascimento() string {
	if x != nil {
		return x.DataNascimento
	}
	return ""
}

type CadastrarAlunoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensagem      string                 `protobuf:"bytes,1,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	Sucesso       bool                   `protobuf:"varint,2,opt,name=sucesso,proto3" json:"sucesso,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CadastrarAlunoResponse) Reset() {
	*x = CadastrarAlunoResponse{}
	mi := &file_ensina_renda_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CadastrarAlunoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CadastrarAlunoResponse) ProtoMessage() {}

func (x *CadastrarAlunoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CadastrarAlunoResponse.ProtoReflect.Descriptor instead.
func (*CadastrarAlunoResponse) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{1}
}

func (x *CadastrarAlunoResponse) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

func (x *CadastrarAlunoResponse) GetSucesso() bool {
	if x != nil {
		return x.Sucesso
	}
	return false
}

type VerificarAlunoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aqui é o hash SHA-256 do email
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Aqui é o hash SHA-256 da senha
	Senha         string `protobuf:"bytes,2,opt,name=senha,proto3" json:"senha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificarAlunoRequest) Reset() {
	*x = VerificarAlunoRequest{}
	mi := &file_ensina_renda_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificarAlunoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificarAlunoRequest) ProtoMessage() {}

func (x *VerificarAlunoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificarAlunoRequest.ProtoReflect.Descriptor instead.
func (*VerificarAlunoRequest) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{2}
}

func (x *VerificarAlunoRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerificarAlunoRequest) GetSenha() string {
	if x != nil {
		return x.Senha
	}
	return ""
}

type VerificarAlunoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensagem      string                 `protobuf:"bytes,1,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	Sucesso       bool                   `protobuf:"varint,2,opt,name=sucesso,proto3" json:"sucesso,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificarAlunoResponse) Reset() {
	*x = VerificarAlunoResponse{}
	mi := &file_ensina_renda_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificarAlunoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificarAlunoResponse) ProtoMessage() {}

func (x *VerificarAlunoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificarAlunoResponse.ProtoReflect.Descriptor instead.
func (*VerificarAlunoResponse) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{3}
}

func (x *VerificarAlunoResponse) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

func (x *VerificarAlunoResponse) GetSucesso() bool {
	if x != nil {
		return x.Sucesso
	}
	return false
}

type RealizarLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aqui é o hash SHA-256 do email
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Aqui é o hash SHA-256 da senha
	Senha         string `protobuf:"bytes,2,opt,name=senha,proto3" json:"senha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealizarLoginRequest) Reset() {
	*x = RealizarLoginRequest{}
	mi := &file_ensina_renda_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealizarLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealizarLoginRequest) ProtoMessage() {}

func (x *RealizarLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealizarLoginRequest.ProtoReflect.Descriptor instead.
func (*RealizarLoginRequest) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{4}
}

func (x *RealizarLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RealizarLoginRequest) GetSenha() string {
	if x != nil {
		return x.Senha
	}
	return ""
}

type RealizarLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Mensagem      string                 `protobuf:"bytes,2,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	Sucesso       bool                   `protobuf:"varint,3,opt,name=sucesso,proto3" json:"sucesso,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealizarLoginResponse) Reset() {
	*x = RealizarLoginResponse{}
	mi := &file_ensina_renda_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealizarLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealizarLoginResponse) ProtoMessage() {}

func (x *RealizarLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealizarLoginResponse.ProtoReflect.Descriptor instead.
func (*RealizarLoginResponse) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{5}
}

func (x *RealizarLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RealizarLoginResponse) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

func (x *RealizarLoginResponse) GetSucesso() bool {
	if x != nil {
		return x.Sucesso
	}
	return false
}

type ConcluirAulaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdAula        int64                  `protobuf:"varint,1,opt,name=id_aula,json=idAula,proto3" json:"id_aula,omitempty"`
	IdUsuario     string                 `protobuf:"bytes,2,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcluirAulaRequest) Reset() {
	*x = ConcluirAulaRequest{}
	mi := &file_ensina_renda_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcluirAulaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcluirAulaRequest) ProtoMessage() {}

func (x *ConcluirAulaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcluirAulaRequest.ProtoReflect.Descriptor instead.
func (*ConcluirAulaRequest) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{6}
}

func (x *ConcluirAulaRequest) GetIdAula() int64 {
	if x != nil {
		return x.IdAula
	}
	return 0
}

func (x *ConcluirAulaRequest) GetIdUsuario() string {
	if x != nil {
		return x.IdUsuario
	}
	return ""
}

type ConcluirAulaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensagem      string                 `protobuf:"bytes,1,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	Sucesso       bool                   `protobuf:"varint,2,opt,name=sucesso,proto3" json:"sucesso,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcluirAulaResponse) Reset() {
	*x = ConcluirAulaResponse{}
	mi := &file_ensina_renda_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcluirAulaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcluirAulaResponse) ProtoMessage() {}

func (x *ConcluirAulaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcluirAulaResponse.ProtoReflect.Descriptor instead.
func (*ConcluirAulaResponse) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{7}
}

func (x *ConcluirAulaResponse) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

func (x *ConcluirAulaResponse) GetSucesso() bool {
	if x != nil {
		return x.Sucesso
	}
	return false
}

type ConcluirModuloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdModulo      string                 `protobuf:"bytes,1,opt,name=id_modulo,json=idModulo,proto3" json:"id_modulo,omitempty"`
	IdUsuario     string                 `protobuf:"bytes,2,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcluirModuloRequest) Reset() {
	*x = ConcluirModuloRequest{}
	mi := &file_ensina_renda_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcluirModuloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcluirModuloRequest) ProtoMessage() {}

func (x *ConcluirModuloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcluirModuloRequest.ProtoReflect.Descriptor instead.
func (*ConcluirModuloRequest) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{8}
}

func (x *ConcluirModuloRequest) GetIdModulo() string {
	if x != nil {
		return x.IdModulo
	}
	return ""
}

func (x *ConcluirModuloRequest) GetIdUsuario() string {
	if x != nil {
		return x.IdUsuario
	}
	return ""
}

type ConcluirModuloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensagem      string                 `protobuf:"bytes,1,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	Sucesso       bool                   `protobuf:"varint,2,opt,name=sucesso,proto3" json:"sucesso,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcluirModuloResponse) Reset() {
	*x = ConcluirModuloResponse{}
	mi := &file_ensina_renda_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcluirModuloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcluirModuloResponse) ProtoMessage() {}

func (x *ConcluirModuloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcluirModuloResponse.ProtoReflect.Descriptor instead.
func (*ConcluirModuloResponse) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{9}
}

func (x *ConcluirModuloResponse) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

func (x *ConcluirModuloResponse) GetSucesso() bool {
	if x != nil {
		return x.Sucesso
	}
	return false
}

type ListarModuloAulasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarModuloAulasRequest) Reset() {
	*x = ListarModuloAulasRequest{}
	mi := &file_ensina_renda_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarModuloAulasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarModuloAulasRequest) ProtoMessage() {}

func (x *ListarModuloAulasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarModuloAulasRequest.ProtoReflect.Descriptor instead.
func (*ListarModuloAulasRequest) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{10}
}

type ListarModuloAulasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuloAulas   []*ModuloAulaAluno     `protobuf:"bytes,1,rep,name=modulo_aulas,json=moduloAulas,proto3" json:"modulo_aulas,omitempty"`
	Mensagem      string                 `protobuf:"bytes,2,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	Sucesso       bool                   `protobuf:"varint,3,opt,name=sucesso,proto3" json:"sucesso,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarModuloAulasResponse) Reset() {
	*x = ListarModuloAulasResponse{}
	mi := &file_ensina_renda_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarModuloAulasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarModuloAulasResponse) ProtoMessage() {}

func (x *ListarModuloAulasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarModuloAulasResponse.ProtoReflect.Descriptor instead.
func (*ListarModuloAulasResponse) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{11}
}

func (x *ListarModuloAulasResponse) GetModuloAulas() []*ModuloAulaAluno {
	if x != nil {
		return x.ModuloAulas
	}
	return nil
}

func (x *ListarModuloAulasResponse) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

func (x *ListarModuloAulasResponse) GetSucesso() bool {
	if x != nil {
		return x.Sucesso
	}
	return false
}

type ModuloAulaAluno struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdModulo      string                 `protobuf:"bytes,1,opt,name=id_modulo,json=idModulo,proto3" json:"id_modulo,omitempty"`
	Aulas         []*Aula                `protobuf:"bytes,2,rep,name=aulas,proto3" json:"aulas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuloAulaAluno) Reset() {
	*x = ModuloAulaAluno{}
	mi := &file_ensina_renda_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuloAulaAluno) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuloAulaAluno) ProtoMessage() {}

func (x *ModuloAulaAluno) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuloAulaAluno.ProtoReflect.Descriptor instead.
func (*ModuloAulaAluno) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{12}
}

func (x *ModuloAulaAluno) GetIdModulo() string {
	if x != nil {
		return x.IdModulo
	}
	return ""
}

func (x *ModuloAulaAluno) GetAulas() []*Aula {
	if x != nil {
		return x.Aulas
	}
	return nil
}

type Aula struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Aula) Reset() {
	*x = Aula{}
	mi := &file_ensina_renda_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Aula) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aula) ProtoMessage() {}

func (x *Aula) ProtoReflect() protoreflect.Message {
	mi := &file_ensina_renda_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aula.ProtoReflect.Descriptor instead.
func (*Aula) Descriptor() ([]byte, []int) {
	return file_ensina_renda_proto_rawDescGZIP(), []int{13}
}

func (x *Aula) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Aula) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_ensina_renda_proto protoreflect.FileDescriptor

const file_ensina_renda_proto_rawDesc = "" +
	"\n" +
	"\x12ensina_renda.proto\x12\fensina_renda\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"\x94\x01\n" +
	"\x15CadastrarAlunoRequest\x12\x17\n" +
	"\x04nome\x18\x01 \x01(\tB\x03\xe0A\x02R\x04nome\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tB\x03\xe0A\x02R\x05email\x12\x19\n" +
	"\x05senha\x18\x03 \x01(\tB\x03\xe0A\x02R\x05senha\x12,\n" +
	"\x0fdata_nascimento\x18\x04 \x01(\tB\x03\xe0A\x02R\x0edataNascimento\"N\n" +
	"\x16CadastrarAlunoResponse\x12\x1a\n" +
	"\bmensagem\x18\x01 \x01(\tR\bmensagem\x12\x18\n" +
	"\asucesso\x18\x02 \x01(\bR\asucesso\"M\n" +
	"\x15VerificarAlunoRequest\x12\x19\n" +
	"\x05email\x18\x01 \x01(\tB\x03\xe0A\x02R\x05email\x12\x19\n" +
	"\x05senha\x18\x02 \x01(\tB\x03\xe0A\x02R\x05senha\"N\n" +
	"\x16VerificarAlunoResponse\x12\x1a\n" +
	"\bmensagem\x18\x01 \x01(\tR\bmensagem\x12\x18\n" +
	"\asucesso\x18\x02 \x01(\bR\asucesso\"L\n" +
	"\x14RealizarLoginRequest\x12\x19\n" +
	"\x05email\x18\x01 \x01(\tB\x03\xe0A\x02R\x05email\x12\x19\n" +
	"\x05senha\x18\x02 \x01(\tB\x03\xe0A\x02R\x05senha\"c\n" +
	"\x15RealizarLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bmensagem\x18\x02 \x01(\tR\bmensagem\x12\x18\n" +
	"\asucesso\x18\x03 \x01(\bR\asucesso\"W\n" +
	"\x13ConcluirAulaRequest\x12\x1c\n" +
	"\aid_aula\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06idAula\x12\"\n" +
	"\n" +
	"id_usuario\x18\x02 \x01(\tB\x03\xe0A\x02R\tidUsuario\"L\n" +
	"\x14ConcluirAulaResponse\x12\x1a\n" +
	"\bmensagem\x18\x01 \x01(\tR\bmensagem\x12\x18\n" +
	"\asucesso\x18\x02 \x01(\bR\asucesso\"]\n" +
	"\x15ConcluirModuloRequest\x12 \n" +
	"\tid_modulo\x18\x01 \x01(\tB\x03\xe0A\x02R\bidModulo\x12\"\n" +
	"\n" +
	"id_usuario\x18\x02 \x01(\tB\x03\xe0A\x02R\tidUsuario\"N\n" +
	"\x16ConcluirModuloResponse\x12\x1a\n" +
	"\bmensagem\x18\x01 \x01(\tR\bmensagem\x12\x18\n" +
	"\asucesso\x18\x02 \x01(\bR\asucesso\"\x1a\n" +
	"\x18ListarModuloAulasRequest\"\x93\x01\n" +
	"\x19ListarModuloAulasResponse\x12@\n" +
	"\fmodulo_aulas\x18\x01 \x03(\v2\x1d.ensina_renda.ModuloAulaAlunoR\vmoduloAulas\x12\x1a\n" +
	"\bmensagem\x18\x02 \x01(\tR\bmensagem\x12\x18\n" +
	"\asucesso\x18\x03 \x01(\bR\asucesso\"X\n" +
	"\x0fModuloAulaAluno\x12\x1b\n" +
	"\tid_modulo\x18\x01 \x01(\tR\bidModulo\x12(\n" +
	"\x05aulas\x18\x02 \x03(\v2\x12.ensina_renda.AulaR\x05aulas\".\n" +
	"\x04Aula\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status2\x99\x06\n" +
	"\x12EnsinaRendaService\x12q\n" +
	"\x0eCadastrarAluno\x12#.ensina_renda.CadastrarAlunoRequest\x1a$.ensina_renda.CadastrarAlunoResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/aluno\x12~\n" +
	"\x0eVerificarAluno\x12#.ensina_renda.VerificarAlunoRequest\x1a$.ensina_renda.VerificarAlunoResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/aluno/{email}/{senha}\x12s\n" +
	"\rRealizarLogin\x12\".ensina_renda.RealizarLoginRequest\x1a#.ensina_renda.RealizarLoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/aluno/auth\x12\x87\x01\n" +
	"\fConcluirAula\x12!.ensina_renda.ConcluirAulaRequest\x1a\".ensina_renda.ConcluirAulaResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/aluno/{id_usuario}/aula/{id_aula}\x12\x91\x01\n" +
	"\x0eConcluirModulo\x12#.ensina_renda.ConcluirModuloRequest\x1a$.ensina_renda.ConcluirModuloResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/v1/aluno/{id_usuario}/modulo/{id_modulo}\x12}\n" +
	"\x11ListarModuloAulas\x12&.ensina_renda.ListarModuloAulasRequest\x1a'.ensina_renda.ListarModuloAulasResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/aluno/aulasB\bZ\x06.;grpcb\x06proto3"

var (
	file_ensina_renda_proto_rawDescOnce sync.Once
	file_ensina_renda_proto_rawDescData []byte
)

func file_ensina_renda_proto_rawDescGZIP() []byte {
	file_ensina_renda_proto_rawDescOnce.Do(func() {
		file_ensina_renda_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ensina_renda_proto_rawDesc), len(file_ensina_renda_proto_rawDesc)))
	})
	return file_ensina_renda_proto_rawDescData
}

var file_ensina_renda_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_ensina_renda_proto_goTypes = []any{
	(*CadastrarAlunoRequest)(nil),     // 0: ensina_renda.CadastrarAlunoRequest
	(*CadastrarAlunoResponse)(nil),    // 1: ensina_renda.CadastrarAlunoResponse
	(*VerificarAlunoRequest)(nil),     // 2: ensina_renda.VerificarAlunoRequest
	(*VerificarAlunoResponse)(nil),    // 3: ensina_renda.VerificarAlunoResponse
	(*RealizarLoginRequest)(nil),      // 4: ensina_renda.RealizarLoginRequest
	(*RealizarLoginResponse)(nil),     // 5: ensina_renda.RealizarLoginResponse
	(*ConcluirAulaRequest)(nil),       // 6: ensina_renda.ConcluirAulaRequest
	(*ConcluirAulaResponse)(nil),      // 7: ensina_renda.ConcluirAulaResponse
	(*ConcluirModuloRequest)(nil),     // 8: ensina_renda.ConcluirModuloRequest
	(*ConcluirModuloResponse)(nil),    // 9: ensina_renda.ConcluirModuloResponse
	(*ListarModuloAulasRequest)(nil),  // 10: ensina_renda.ListarModuloAulasRequest
	(*ListarModuloAulasResponse)(nil), // 11: ensina_renda.ListarModuloAulasResponse
	(*ModuloAulaAluno)(nil),           // 12: ensina_renda.ModuloAulaAluno
	(*Aula)(nil),                      // 13: ensina_renda.Aula
}
var file_ensina_renda_proto_depIdxs = []int32{
	12, // 0: ensina_renda.ListarModuloAulasResponse.modulo_aulas:type_name -> ensina_renda.ModuloAulaAluno
	13, // 1: ensina_renda.ModuloAulaAluno.aulas:type_name -> ensina_renda.Aula
	0,  // 2: ensina_renda.EnsinaRendaService.CadastrarAluno:input_type -> ensina_renda.CadastrarAlunoRequest
	2,  // 3: ensina_renda.EnsinaRendaService.VerificarAluno:input_type -> ensina_renda.VerificarAlunoRequest
	4,  // 4: ensina_renda.EnsinaRendaService.RealizarLogin:input_type -> ensina_renda.RealizarLoginRequest
	6,  // 5: ensina_renda.EnsinaRendaService.ConcluirAula:input_type -> ensina_renda.ConcluirAulaRequest
	8,  // 6: ensina_renda.EnsinaRendaService.ConcluirModulo:input_type -> ensina_renda.ConcluirModuloRequest
	10, // 7: ensina_renda.EnsinaRendaService.ListarModuloAulas:input_type -> ensina_renda.ListarModuloAulasRequest
	1,  // 8: ensina_renda.EnsinaRendaService.CadastrarAluno:output_type -> ensina_renda.CadastrarAlunoResponse
	3,  // 9: ensina_renda.EnsinaRendaService.VerificarAluno:output_type -> ensina_renda.VerificarAlunoResponse
	5,  // 10: ensina_renda.EnsinaRendaService.RealizarLogin:output_type -> ensina_renda.RealizarLoginResponse
	7,  // 11: ensina_renda.EnsinaRendaService.ConcluirAula:output_type -> ensina_renda.ConcluirAulaResponse
	9,  // 12: ensina_renda.EnsinaRendaService.ConcluirModulo:output_type -> ensina_renda.ConcluirModuloResponse
	11, // 13: ensina_renda.EnsinaRendaService.ListarModuloAulas:output_type -> ensina_renda.ListarModuloAulasResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_ensina_renda_proto_init() }
func file_ensina_renda_proto_init() {
	if File_ensina_renda_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ensina_renda_proto_rawDesc), len(file_ensina_renda_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ensina_renda_proto_goTypes,
		DependencyIndexes: file_ensina_renda_proto_depIdxs,
		MessageInfos:      file_ensina_renda_proto_msgTypes,
	}.Build()
	File_ensina_renda_proto = out.File
	file_ensina_renda_proto_goTypes = nil
	file_ensina_renda_proto_depIdxs = nil
}
